create_clock -period 20.000 [get_ports i_fpga_sysclk50m]
create_clock -period 10.000 [get_ports i_clk_100mhz_p]
create_clock -period 8.138 [get_ports i_clk_122_88_mhz_p]

# Transceiver reference clock
create_clock -period 4.069 -name refclk_b130 [get_ports gty_refclk2p]
create_clock -period 4.069 -name refclk_b131 [get_ports gty_refclk3p]


# The following GT Common input ports change with line rate, to avoid Vivado warnings set to absolute value for timing analysis.
#set_case_analysis 0 [get_pins -filter {REF_PIN_NAME =~ SDM0DATA[*]} -of [get_cells -hier -filter {name =~ *gt*e*_common_gen.GT*E*_COMMON_PRIM_INST}]]
#
set_false_path -from [get_pins {u*_cpri_top/*.nodebfn_valid_reg[*]/C}] -to [get_pins {u*_cpri_top/*.gnrl_nodebfn_valid/bit_pipe_reg[*]/D}]

set_false_path -from [get_pins {u*_cpri_top/u_cpri_ch*/ch*_cpri/U0/cpri_i/cpri_i/link_manager_i/stat_code_i_reg[*]/C}] -to [get_pins {u*_cpri_top/IQ_ETH_GEN*.nodebfn_valid_reg[*]/D}]
set_false_path -from [get_pins {u*_cpri_top/u_cpri_ch*/ch*_cpri/U0/*/cpri_i/cpri_i/link_manager_i/stat_code_i_reg[*]/C}] -to [get_pins {u*_cpri_top/IQ_ETH_GEN*.nodebfn_valid_reg[*]/D}]

set_false_path -from [get_pins {u*_sys_tbu/u_sys_frame_info_gen*/o_frame_num_reg[*]/C}] -to [get_pins {u*_cpri_top/u*_iq_gen_tbu/o_nodebfn_tx_nr_reg[*]/D}]
set_false_path -from [get_pins u*_sys_tbu/u_sys_frame_info_gen*/o_frame_head_reg/C] -to [get_pins u*_cpri_top/u*_iq_gen_tbu/ref_10ms_hd*/D]
set_false_path -from [get_pins {u1_cpri_top/u_cpri*/u_tx_pole_vio/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[*].PROBE_OUT*_INST/Probe_out_reg[*]/C}] 
set_false_path -from [get_pins {u1_cpri_top/vio_top/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[0].PROBE_OUT0_INST/Probe_out_reg[0]/C}] -to [get_pins u*_cpri_top/u_clk_gen/u*_rst_sync/*rst*/PRE]
#set_false_path -from [get_pins {IQ_ETH_GEN*.nodebfn_valid_reg[*]/C}] -to [get_pins {IQ_ETH_GEN*.u_eth_mii_test/mii_state_reg[*]/CE}]
#set_false_path -from [get_pins {IQ_ETH_GEN*.nodebfn_valid_reg[*]/C}] -to [get_pins {IQ_ETH_GEN*.u_eth_mii_test/frame_fcs_reg[*]/R}]
#set_false_path -from [get_pins {IQ_ETH_GEN*.nodebfn_valid_reg[*]/C}] -to [get_pins {IQ_ETH_GEN*.u_eth_mii_test/frame_fcs_reg[*]/CE}]

set_false_path -to [get_pins u_ila*/inst/PROBE_PIPE.shift_probes*/D]
# The following GT Common input ports change with line rate, to avoid Vivado warnings set to absolute value for timing analysis.
#set_case_analysis 0 [get_pins -filter {REF_PIN_NAME =~ SDM0DATA[*]} -of [get_cells -hier -filter {name =~ *gt*e*_common_gen.GT*E*_COMMON_PRIM_INST}]]
#
set_property MARK_DEBUG true [get_nets u_clk_245p76_gen/inst/locked]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx_enable[0]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/i_ref_frame_num[0]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/i_ref_frame_num[3]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/i_ref_frame_num[5]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/i_ref_frame_num[7]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/i_ref_frame_num[1]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/i_ref_frame_num[2]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/i_ref_frame_num[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/i_ref_frame_num[6]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/i_ref_frame_num[8]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/i_ref_frame_num[9]}]
set_property MARK_DEBUG true [get_nets u1_cpri_top/i_ref_10ms_head]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[26]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[32]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[49]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[53]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[28]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[29]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[31]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[34]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[45]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[62]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[17]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[22]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[37]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[38]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[43]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[46]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[55]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[57]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[2]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[6]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[13]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[20]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[23]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[30]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[33]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[35]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[51]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[1]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[3]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[15]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[36]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[47]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[54]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[56]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[8]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[19]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[41]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[44]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[48]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[52]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[61]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[63]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[7]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[14]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[21]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[24]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[25]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[27]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[39]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[58]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[0]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[10]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[11]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[16]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[40]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[42]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[50]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[59]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[60]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[5]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[9]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[12]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_tx[0]_89[18]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_tx_nr[0]_88[2]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_tx_nr[0]_88[6]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_tx_nr[0]_88[7]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_tx_nr[0]_88[0]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_tx_nr[0]_88[1]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_tx_nr[0]_88[3]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_tx_nr[0]_88[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_tx_nr[0]_88[5]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_tx_nr[0]_88[8]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_tx_nr[0]_88[9]}]
set_property MARK_DEBUG true [get_nets u1_cpri_top/nodebfn_tx_strobe_0]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/bffw[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_valid[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[7]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[24]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[33]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[43]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[44]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[59]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[19]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[8]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[35]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[36]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[49]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[52]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[2]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[23]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[14]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[29]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[47]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[55]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[32]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[37]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[3]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[11]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[42]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[46]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[50]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[54]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[62]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[60]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[6]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[26]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[15]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[21]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[9]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[20]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[27]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[41]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[51]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[56]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[63]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[34]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[13]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[17]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[18]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[30]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[40]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[38]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[58]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[48]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[0]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[5]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[31]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[45]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[39]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[61]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[1]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[25]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[53]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[57]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[10]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[28]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[12]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[16]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx[4]_80[22]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[0]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[7]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[8]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[10]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[1]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[2]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[3]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[5]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[6]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[9]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_nr[4]_84[11]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/nodebfn_rx_strobe[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[10]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[11]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[22]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[24]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[25]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[27]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[31]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[3]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[9]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[12]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[17]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[21]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[23]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[29]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[30]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[5]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[13]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[16]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[20]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[26]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[28]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[2]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[0]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[1]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[6]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[7]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[8]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[18]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[14]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[15]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_error_count[4]_21[19]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[1]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[2]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[6]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[12]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[24]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[27]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[28]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[31]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[3]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[11]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[13]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[16]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[19]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[22]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[26]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[5]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[7]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[9]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[14]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[23]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[29]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[0]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[8]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[30]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[10]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[15]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[17]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[18]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[20]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[21]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_frame_count[4]_22[25]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[0]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[1]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[3]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[4]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[5]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[10]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[11]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[2]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[6]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[7]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[8]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[9]}]
set_property MARK_DEBUG true [get_nets {u1_cpri_top/iq_rx_word_err[4]}]
connect_debug_port u_ila_0/probe1 [get_nets [list {u1_cpri_top/iq_tx[0]_89[0]} {u1_cpri_top/iq_tx[0]_89[1]} {u1_cpri_top/iq_tx[0]_89[2]} {u1_cpri_top/iq_tx[0]_89[3]} {u1_cpri_top/iq_tx[0]_89[4]} {u1_cpri_top/iq_tx[0]_89[5]} {u1_cpri_top/iq_tx[0]_89[6]} {u1_cpri_top/iq_tx[0]_89[7]} {u1_cpri_top/iq_tx[0]_89[8]} {u1_cpri_top/iq_tx[0]_89[9]} {u1_cpri_top/iq_tx[0]_89[10]} {u1_cpri_top/iq_tx[0]_89[11]} {u1_cpri_top/iq_tx[0]_89[12]} {u1_cpri_top/iq_tx[0]_89[13]} {u1_cpri_top/iq_tx[0]_89[14]} {u1_cpri_top/iq_tx[0]_89[15]} {u1_cpri_top/iq_tx[0]_89[16]} {u1_cpri_top/iq_tx[0]_89[17]} {u1_cpri_top/iq_tx[0]_89[18]} {u1_cpri_top/iq_tx[0]_89[19]} {u1_cpri_top/iq_tx[0]_89[20]} {u1_cpri_top/iq_tx[0]_89[21]} {u1_cpri_top/iq_tx[0]_89[22]} {u1_cpri_top/iq_tx[0]_89[23]} {u1_cpri_top/iq_tx[0]_89[24]} {u1_cpri_top/iq_tx[0]_89[25]} {u1_cpri_top/iq_tx[0]_89[26]} {u1_cpri_top/iq_tx[0]_89[27]} {u1_cpri_top/iq_tx[0]_89[28]} {u1_cpri_top/iq_tx[0]_89[29]} {u1_cpri_top/iq_tx[0]_89[30]} {u1_cpri_top/iq_tx[0]_89[31]} {u1_cpri_top/iq_tx[0]_89[32]} {u1_cpri_top/iq_tx[0]_89[33]} {u1_cpri_top/iq_tx[0]_89[34]} {u1_cpri_top/iq_tx[0]_89[35]} {u1_cpri_top/iq_tx[0]_89[36]} {u1_cpri_top/iq_tx[0]_89[37]} {u1_cpri_top/iq_tx[0]_89[38]} {u1_cpri_top/iq_tx[0]_89[39]} {u1_cpri_top/iq_tx[0]_89[40]} {u1_cpri_top/iq_tx[0]_89[41]} {u1_cpri_top/iq_tx[0]_89[42]} {u1_cpri_top/iq_tx[0]_89[43]} {u1_cpri_top/iq_tx[0]_89[44]} {u1_cpri_top/iq_tx[0]_89[45]} {u1_cpri_top/iq_tx[0]_89[46]} {u1_cpri_top/iq_tx[0]_89[47]} {u1_cpri_top/iq_tx[0]_89[48]} {u1_cpri_top/iq_tx[0]_89[49]} {u1_cpri_top/iq_tx[0]_89[50]} {u1_cpri_top/iq_tx[0]_89[51]} {u1_cpri_top/iq_tx[0]_89[52]} {u1_cpri_top/iq_tx[0]_89[53]} {u1_cpri_top/iq_tx[0]_89[54]} {u1_cpri_top/iq_tx[0]_89[55]} {u1_cpri_top/iq_tx[0]_89[56]} {u1_cpri_top/iq_tx[0]_89[57]} {u1_cpri_top/iq_tx[0]_89[58]} {u1_cpri_top/iq_tx[0]_89[59]} {u1_cpri_top/iq_tx[0]_89[60]} {u1_cpri_top/iq_tx[0]_89[61]} {u1_cpri_top/iq_tx[0]_89[62]} {u1_cpri_top/iq_tx[0]_89[63]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {u1_cpri_top/nodebfn_tx_nr[0]_88[0]} {u1_cpri_top/nodebfn_tx_nr[0]_88[1]} {u1_cpri_top/nodebfn_tx_nr[0]_88[2]} {u1_cpri_top/nodebfn_tx_nr[0]_88[3]} {u1_cpri_top/nodebfn_tx_nr[0]_88[4]} {u1_cpri_top/nodebfn_tx_nr[0]_88[5]} {u1_cpri_top/nodebfn_tx_nr[0]_88[6]} {u1_cpri_top/nodebfn_tx_nr[0]_88[7]} {u1_cpri_top/nodebfn_tx_nr[0]_88[8]} {u1_cpri_top/nodebfn_tx_nr[0]_88[9]}]]
connect_debug_port u_ila_1/probe0 [get_nets [list {u1_cpri_top/iq_rx_error_count[4]_21[0]} {u1_cpri_top/iq_rx_error_count[4]_21[1]} {u1_cpri_top/iq_rx_error_count[4]_21[2]} {u1_cpri_top/iq_rx_error_count[4]_21[3]} {u1_cpri_top/iq_rx_error_count[4]_21[4]} {u1_cpri_top/iq_rx_error_count[4]_21[5]} {u1_cpri_top/iq_rx_error_count[4]_21[6]} {u1_cpri_top/iq_rx_error_count[4]_21[7]} {u1_cpri_top/iq_rx_error_count[4]_21[8]} {u1_cpri_top/iq_rx_error_count[4]_21[9]} {u1_cpri_top/iq_rx_error_count[4]_21[10]} {u1_cpri_top/iq_rx_error_count[4]_21[11]} {u1_cpri_top/iq_rx_error_count[4]_21[12]} {u1_cpri_top/iq_rx_error_count[4]_21[13]} {u1_cpri_top/iq_rx_error_count[4]_21[14]} {u1_cpri_top/iq_rx_error_count[4]_21[15]} {u1_cpri_top/iq_rx_error_count[4]_21[16]} {u1_cpri_top/iq_rx_error_count[4]_21[17]} {u1_cpri_top/iq_rx_error_count[4]_21[18]} {u1_cpri_top/iq_rx_error_count[4]_21[19]} {u1_cpri_top/iq_rx_error_count[4]_21[20]} {u1_cpri_top/iq_rx_error_count[4]_21[21]} {u1_cpri_top/iq_rx_error_count[4]_21[22]} {u1_cpri_top/iq_rx_error_count[4]_21[23]} {u1_cpri_top/iq_rx_error_count[4]_21[24]} {u1_cpri_top/iq_rx_error_count[4]_21[25]} {u1_cpri_top/iq_rx_error_count[4]_21[26]} {u1_cpri_top/iq_rx_error_count[4]_21[27]} {u1_cpri_top/iq_rx_error_count[4]_21[28]} {u1_cpri_top/iq_rx_error_count[4]_21[29]} {u1_cpri_top/iq_rx_error_count[4]_21[30]} {u1_cpri_top/iq_rx_error_count[4]_21[31]}]]
connect_debug_port u_ila_1/probe1 [get_nets [list {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[0]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[1]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[2]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[3]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[4]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[5]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[6]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[7]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[8]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[9]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[10]} {u1_cpri_top/iq_rx_nodebfn_rx_nr_store[4]_20[11]}]]
connect_debug_port u_ila_1/probe3 [get_nets [list {u1_cpri_top/nodebfn_rx_nr[4]_84[0]} {u1_cpri_top/nodebfn_rx_nr[4]_84[1]} {u1_cpri_top/nodebfn_rx_nr[4]_84[2]} {u1_cpri_top/nodebfn_rx_nr[4]_84[3]} {u1_cpri_top/nodebfn_rx_nr[4]_84[4]} {u1_cpri_top/nodebfn_rx_nr[4]_84[5]} {u1_cpri_top/nodebfn_rx_nr[4]_84[6]} {u1_cpri_top/nodebfn_rx_nr[4]_84[7]} {u1_cpri_top/nodebfn_rx_nr[4]_84[8]} {u1_cpri_top/nodebfn_rx_nr[4]_84[9]} {u1_cpri_top/nodebfn_rx_nr[4]_84[10]} {u1_cpri_top/nodebfn_rx_nr[4]_84[11]}]]
connect_debug_port u_ila_1/probe5 [get_nets [list {u1_cpri_top/iq_rx_frame_count[4]_22[0]} {u1_cpri_top/iq_rx_frame_count[4]_22[1]} {u1_cpri_top/iq_rx_frame_count[4]_22[2]} {u1_cpri_top/iq_rx_frame_count[4]_22[3]} {u1_cpri_top/iq_rx_frame_count[4]_22[4]} {u1_cpri_top/iq_rx_frame_count[4]_22[5]} {u1_cpri_top/iq_rx_frame_count[4]_22[6]} {u1_cpri_top/iq_rx_frame_count[4]_22[7]} {u1_cpri_top/iq_rx_frame_count[4]_22[8]} {u1_cpri_top/iq_rx_frame_count[4]_22[9]} {u1_cpri_top/iq_rx_frame_count[4]_22[10]} {u1_cpri_top/iq_rx_frame_count[4]_22[11]} {u1_cpri_top/iq_rx_frame_count[4]_22[12]} {u1_cpri_top/iq_rx_frame_count[4]_22[13]} {u1_cpri_top/iq_rx_frame_count[4]_22[14]} {u1_cpri_top/iq_rx_frame_count[4]_22[15]} {u1_cpri_top/iq_rx_frame_count[4]_22[16]} {u1_cpri_top/iq_rx_frame_count[4]_22[17]} {u1_cpri_top/iq_rx_frame_count[4]_22[18]} {u1_cpri_top/iq_rx_frame_count[4]_22[19]} {u1_cpri_top/iq_rx_frame_count[4]_22[20]} {u1_cpri_top/iq_rx_frame_count[4]_22[21]} {u1_cpri_top/iq_rx_frame_count[4]_22[22]} {u1_cpri_top/iq_rx_frame_count[4]_22[23]} {u1_cpri_top/iq_rx_frame_count[4]_22[24]} {u1_cpri_top/iq_rx_frame_count[4]_22[25]} {u1_cpri_top/iq_rx_frame_count[4]_22[26]} {u1_cpri_top/iq_rx_frame_count[4]_22[27]} {u1_cpri_top/iq_rx_frame_count[4]_22[28]} {u1_cpri_top/iq_rx_frame_count[4]_22[29]} {u1_cpri_top/iq_rx_frame_count[4]_22[30]} {u1_cpri_top/iq_rx_frame_count[4]_22[31]}]]
connect_debug_port u_ila_1/probe6 [get_nets [list {u1_cpri_top/iq_rx[4]_80[0]} {u1_cpri_top/iq_rx[4]_80[1]} {u1_cpri_top/iq_rx[4]_80[2]} {u1_cpri_top/iq_rx[4]_80[3]} {u1_cpri_top/iq_rx[4]_80[4]} {u1_cpri_top/iq_rx[4]_80[5]} {u1_cpri_top/iq_rx[4]_80[6]} {u1_cpri_top/iq_rx[4]_80[7]} {u1_cpri_top/iq_rx[4]_80[8]} {u1_cpri_top/iq_rx[4]_80[9]} {u1_cpri_top/iq_rx[4]_80[10]} {u1_cpri_top/iq_rx[4]_80[11]} {u1_cpri_top/iq_rx[4]_80[12]} {u1_cpri_top/iq_rx[4]_80[13]} {u1_cpri_top/iq_rx[4]_80[14]} {u1_cpri_top/iq_rx[4]_80[15]} {u1_cpri_top/iq_rx[4]_80[16]} {u1_cpri_top/iq_rx[4]_80[17]} {u1_cpri_top/iq_rx[4]_80[18]} {u1_cpri_top/iq_rx[4]_80[19]} {u1_cpri_top/iq_rx[4]_80[20]} {u1_cpri_top/iq_rx[4]_80[21]} {u1_cpri_top/iq_rx[4]_80[22]} {u1_cpri_top/iq_rx[4]_80[23]} {u1_cpri_top/iq_rx[4]_80[24]} {u1_cpri_top/iq_rx[4]_80[25]} {u1_cpri_top/iq_rx[4]_80[26]} {u1_cpri_top/iq_rx[4]_80[27]} {u1_cpri_top/iq_rx[4]_80[28]} {u1_cpri_top/iq_rx[4]_80[29]} {u1_cpri_top/iq_rx[4]_80[30]} {u1_cpri_top/iq_rx[4]_80[31]} {u1_cpri_top/iq_rx[4]_80[32]} {u1_cpri_top/iq_rx[4]_80[33]} {u1_cpri_top/iq_rx[4]_80[34]} {u1_cpri_top/iq_rx[4]_80[35]} {u1_cpri_top/iq_rx[4]_80[36]} {u1_cpri_top/iq_rx[4]_80[37]} {u1_cpri_top/iq_rx[4]_80[38]} {u1_cpri_top/iq_rx[4]_80[39]} {u1_cpri_top/iq_rx[4]_80[40]} {u1_cpri_top/iq_rx[4]_80[41]} {u1_cpri_top/iq_rx[4]_80[42]} {u1_cpri_top/iq_rx[4]_80[43]} {u1_cpri_top/iq_rx[4]_80[44]} {u1_cpri_top/iq_rx[4]_80[45]} {u1_cpri_top/iq_rx[4]_80[46]} {u1_cpri_top/iq_rx[4]_80[47]} {u1_cpri_top/iq_rx[4]_80[48]} {u1_cpri_top/iq_rx[4]_80[49]} {u1_cpri_top/iq_rx[4]_80[50]} {u1_cpri_top/iq_rx[4]_80[51]} {u1_cpri_top/iq_rx[4]_80[52]} {u1_cpri_top/iq_rx[4]_80[53]} {u1_cpri_top/iq_rx[4]_80[54]} {u1_cpri_top/iq_rx[4]_80[55]} {u1_cpri_top/iq_rx[4]_80[56]} {u1_cpri_top/iq_rx[4]_80[57]} {u1_cpri_top/iq_rx[4]_80[58]} {u1_cpri_top/iq_rx[4]_80[59]} {u1_cpri_top/iq_rx[4]_80[60]} {u1_cpri_top/iq_rx[4]_80[61]} {u1_cpri_top/iq_rx[4]_80[62]} {u1_cpri_top/iq_rx[4]_80[63]}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u1_cpri_top/u_cpri_ch_3_0/ch0_cpri/U0/cpri_shared_clocks_i/txusrclk2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {u1_cpri_top/iq_tx_enable[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {u1_cpri_top/i_ref_frame_num[0]} {u1_cpri_top/i_ref_frame_num[1]} {u1_cpri_top/i_ref_frame_num[2]} {u1_cpri_top/i_ref_frame_num[3]} {u1_cpri_top/i_ref_frame_num[4]} {u1_cpri_top/i_ref_frame_num[5]} {u1_cpri_top/i_ref_frame_num[6]} {u1_cpri_top/i_ref_frame_num[7]} {u1_cpri_top/i_ref_frame_num[8]} {u1_cpri_top/i_ref_frame_num[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list u1_cpri_top/i_ref_10ms_head]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list u_clk_245p76_gen/inst/locked]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list u1_cpri_top/nodebfn_tx_strobe_0]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list u1_cpri_top/u_cpri_ch_7_4/ch0_cpri/U0/cpri_shared_clocks_i/txusrclk2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {u1_cpri_top/nodebfn_rx_strobe[4]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets i_fpga_sysclk50m_IBUF]
